### PR TITLE
Add flag to ignore specific dependency updates (blacklist)

### PR DESCRIPTION
**Pull request by usr42**
Some dependencies you don't want to upgrade, because there are known issues or incompatibilities. These dependencies you want to blacklist.

This PR allows to blacklist dependencies via command-line parameters.
It is pretty similar to and inspired by PR https://github.com/patrikerdes/gradle-use-latest-versions-plugin/pull/27 (Add flag to update only explicitly listed dependencies).

### CODE REVIEW

**Comment by usr42** [comment]
I'm going to add also the option to match the blacklist and whitelist by `group`, not just the `group:name` combination. 
E.g. `junit` would match everything with the group `junit` for instance `junit:junit`

**Comment by usr42** [comment]
> Thanks, this looks great. Could you update the README with the new functionality introduced in the second commit?

Done

**Comment by usr42** [comment]
@patrikerdes Is there something else to change from your perspective?

**Comment by patrikerdes** [comment]
I'll release a new version sometime this weekend. Thanks again!

**Comment by usr42** [comment]
> I'll release a new version sometime this weekend. Thanks again!

Awesome! 👍

**Comment by Xerus2000** [comment]
Would be nice if this blacklist could somehow be persisted so that you wouldn't have to specify it all the time - maybe in the `gradle` folder or better yet in the buildscript.

**Pull request merged**
